config/routes.rb
Rails.application.routes.draw do
resources :years do
  resources :weeks, only: :show
end

resources :weeks do
  resources :shifts
  member do
    post 'create_shifts'
    post 'balance_schedule'
  end
end
  

  resources :assignments

  resources :periods
  resources :nurses

  resources :shifts do
    resources :assignments, only: [:create]
    # post 'assigns/new', to: 'assignments#create'
  end 

  # resources :shifts

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "years#index"
end
=begin
 /shifts/:shift_id/assigns(.:format)      

 Started POST "/shifts/16/assigns/new" for ::1 at 2023-01-20 13:15:46 -0800
  
ActionController::RoutingError (No route matches [POST] "/shifts/16/assigns/new"):
=end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :year

  has_many :shifts, dependent: :destroy
  accepts_nested_attributes_for :shifts

  #after_create :create_shifts

  @nurses = Nurse.all
  @total_nurses = @nurses.count
  
  def self.create_shifts(w)
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

    (0..6).each do |day|
      Shift.create!(week_id: w.id, name: days[day])
    end
  end

  
  def self.nurses_needed( nurses_per_day)
    @total_assignments_needed = nurses_per_day.sum
    @total_assignments_available = @total_nurses * 3
   
    if  @total_assignments_available >= @total_assignments_needed
      3
    elsif @total_assignments_needed > @total_assignments_available
      p "#{ (@total_assignments_needed - @total_nurses) * 12 } hours needed of overtime"
       ((((@total_assignments_needed)/3.0).ceil).to_f / @total_nurses).ceil + 3
    end
  end

  def self.create_shifts_nurses_hash(week)
    shift_hash = {}
    shifts = week.shifts

    shifts.each do |shift|
      shift_hash[shift.id] = shift.nurses.pluck(:name)
    end
    shift_hash
  end

  def self.nurse_days_worked(week)
    schedule = self.create_shifts_nurses_hash(week)
    days_worked = {}
    
     @nurses.each do |nurse|
      total = 0
     
      schedule.each do |shift, nurses|
        if nurses.include?(nurse.name)
          total += 1
        end
      end
      days_worked[nurse.name] = total
    end
    days_worked
  end

  def self.balance_schedule(w)
    nurses_per_day = [10, 10, 10, 10, 10, 10, 10]
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    schedule = self.create_shifts_nurses_hash(w)
    days_worked = self.nurse_days_worked(w)
    @shifts_per_nurse_needed = self.nurses_needed( [10, 10, 10, 10, 10, 10, 10])

    last_weekend_nurse = nil

     nurses = Nurse.all.map(&:name)

    (0..6).each do |day|
      (1..nurses_per_day[day]).each do |nurse_number|
        nurse = nil
        if nurse.nil? 
          nurse = nurses.shift
          if nurses.empty?
            nurses = Nurse.all.reverse.map(&:name)
          end
          if days_worked[nurse] >= @shifts_per_nurse_needed
            nurse = nil
          end

          schedule[schedule.keys[day]] << nurse

          shift_id = Shift.find_by(id: schedule.keys[day]).id
          nurse_id = Nurse.find_by(name: nurse).id
          Assignment.create!(shift_id: shift_id, nurse_id: nurse_id  )
          days_worked[nurse] += 1
        end
      end
    end
    schedule
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: %i[ show edit update destroy balance_schedule create_shifts ]

  # GET /weeks or /weeks.json
  def index
    @weeks = Week.all
  end

  # GET /weeks/1 or /weeks/1.json
  def show
  end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit
  end

  # POST /weeks or /weeks.json
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        format.html { redirect_to week_url(@week), notice: "Week was successfully created." }
        format.json { render :show, status: :created, location: @week }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeks/1 or /weeks/1.json
  def update
    respond_to do |format|
      if @week.update(week_params)
        format.html { redirect_to week_url(@week), notice: "Week was successfully updated." }
        format.json { render :show, status: :ok, location: @week }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1 or /weeks/1.json
  def destroy
    @week.destroy

    respond_to do |format|
      format.html { redirect_to weeks_url, notice: "Week was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def create_shifts
    @schedule = Week.create_shifts(@week)
  end

  def balance_schedule
    @schedule = Week.balance_schedule(@week)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def week_params
      params.require(:week).permit(:week_number, :start_date, :end_date, :year_id)
    end
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.erb
<%= form_with(model: week) do |form| %>
  <% if week.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
        <% week.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :week_number, style: "display: block" %>
    <%= form.number_field :week_number %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :year_id, style: "display: block" %>
    <%= form.text_field :year_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weeks/_week.html.erb
<div id="<%= dom_id week %>">
  <p>
    <strong>Week:</strong>
    <%= week.week_number %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= week.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= week.end_date %>
  </p>
</div>

app/views/weeks/edit.html.erb
<h1>Editing week</h1>

<%= render "form", week: @week %>

<br>

<div>
  <%= link_to "Show this week", @week %> |
  <%= link_to "Back to weeks", weeks_path %>
</div>

app/views/weeks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weeks</h1>

<div id="weeks">
  <% @weeks.each do |week| %>
    <%= render week %>
    <p>
      <%= link_to "Show this week", week %>
    </p>
  <% end %>
</div>

<%= link_to "New week", new_week_path %>

app/views/weeks/new.html.erb
<h1>New week</h1>

<%= render "form", week: @week %>

<br>

<div>
  <%= link_to "Back to weeks", weeks_path %>
</div>

app/views/weeks/show.html.erb
<%= link_to 'Years', years_path , class:'' %>
<p style="color: green"><%= notice %></p>

<%= render @week %>
<br>


<br>
 

<%= button_to 'Create Shifts', create_shifts_week_path , class:'' %> <br>
<%= button_to 'balance schedule', balance_schedule_week_path , class:'' %> <br>

<br>

<br>
<% @week.shifts.each do |n|  %>
  <%= link_to  Date.parse(n.date).strftime("%A"), shift_path(n) %> <br>
<% end %>

<br>
<div>
  <%= link_to "Edit this week", edit_week_path(@week) %> |
  <%= link_to "Back to Year", year_path(@week.year) %>

  <%= button_to "Destroy this week", @week, method: :delete %>
</div>