config/routes.rb
Rails.application.routes.draw do
resources :years do
  resources :weeks, only: :show
end

resources :weeks do
  resources :shifts
  member do
    post 'create_shifts'
    post 'balance_schedule'
  end
end
  

  resources :assignments

  resources :periods
  resources :nurses

  resources :shifts do
    resources :assignments, only: [:create]
    # post 'assigns/new', to: 'assignments#create'
  end 

  # resources :shifts

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "years#index"
end
=begin
 /shifts/:shift_id/assigns(.:format)      

 Started POST "/shifts/16/assigns/new" for ::1 at 2023-01-20 13:15:46 -0800
  
ActionController::RoutingError (No route matches [POST] "/shifts/16/assigns/new"):
=end

app/models/period.rb
class Period < ApplicationRecord
  has_many :shifts
  accepts_nested_attributes_for :shifts

  after_create :create_shifts


  def create_shifts
    start_date = self.begining_date
    end_date = self.end_date
    (start_date..end_date).each do |date|
      Shift.create!(period_id: self.id, date: date)
    end
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: %i[ show edit update destroy ]

  # GET /periods or /periods.json
  def index
    @periods = Period.all
  end

  # GET /periods/1 or /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods or /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to period_url(@period), notice: "Period was successfully created." }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1 or /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to period_url(@period), notice: "Period was successfully updated." }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1 or /periods/1.json
  def destroy
    @period.destroy

    respond_to do |format|
      format.html { redirect_to periods_url, notice: "Period was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def period_params
      params.require(:period).permit(:name, :number, :begining_date, :end_date)
    end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_with(model: period) do |form| %>
  <% if period.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
        <% period.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :begining_date, style: "display: block" %>
    <%= form.date_field :begining_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/periods/_period.html.erb
<div id="<%= dom_id period %>">
  <p>
    <strong>Name:</strong>
    <%= period.name %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= period.number %>
  </p>

  <p>
    <strong>Begining date:</strong>
    <%= period.begining_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= period.end_date %>
  </p>

</div>

app/views/periods/edit.html.erb
<h1>Editing period</h1>

<%= render "form", period: @period %>

<br>

<div>
  <%= link_to "Show this period", @period %> |
  <%= link_to "Back to periods", periods_path %>
</div>

app/views/periods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Periods</h1>
<h4>A period is a two week period</h4>
<h3><%= link_to "New period", new_period_path %></h3>
<div id="periods">
  <% @periods.each do |period| %>
    <%= render period %>
    <p>
      <%= link_to "Show this period", period %>
    </p>
  <% end %>
</div>

app/views/periods/new.html.erb
<h1>New period</h1>

<%= render "form", period: @period %>

<br>

<div>
  <%= link_to "Back to periods", periods_path %>
</div>

app/views/periods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @period %>
<br>

<% @period.shifts.each do |shift| %>
  <%= link_to shift.date, shift_path(shift) %> <br>
<% end %>


<div>
  <%= link_to "Edit this period", edit_period_path(@period) %> |
  <%= link_to "Back to periods", periods_path %>
  <%= button_to "Destroy this period", @period, method: :delete %>
</div>