config/routes.rb
Rails.application.routes.draw do
resources :years do
  resources :weeks, only: :show
end

resources :weeks do
  resources :shifts
  member do
    post 'create_shifts'
    post 'balance_schedule'
  end
end
  

  resources :assignments

  resources :periods
  resources :nurses

  resources :shifts do
    resources :assignments, only: [:create]
    # post 'assigns/new', to: 'assignments#create'
  end 

  # resources :shifts

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "years#index"
end
=begin
 /shifts/:shift_id/assigns(.:format)      

 Started POST "/shifts/16/assigns/new" for ::1 at 2023-01-20 13:15:46 -0800
  
ActionController::RoutingError (No route matches [POST] "/shifts/16/assigns/new"):
=end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :week
  has_many :assignments, dependent: :destroy
  has_many :nurses, through: :assignments
  accepts_nested_attributes_for :assignments

  def unassigned_nurses
    Nurse.all - self.nurses
  end
end

app/controllers/shifts/assignments_controller.rb
class Shift::AssignmentsController < ApplicationController
# class Dashboard::ProfileController < ApplicationController

  def create
    @shift = Shift.find(params[:shift_id])
    @nurse = Nurse.find(params[:nurse_id])
    @assign = Assign.new(shift_id: @shift.id, nurse_id: @nurse.id)
    if @assignment.save
      flash[:success] = "Nurse successfully added to shift"
      redirect_to @assignment.shift
    else
      flash.now[:danger] = "Failed to add nurse to shift"
      render 'new'
    end
  end



  def assignment_params
    params.require(:assignment).permit(:details, :nurse_id, :shift_id, nurse_ids: [])
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[ show edit update destroy ]

  # GET /shifts or /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1 or /shifts/1.json
  def show
    @nurses = Nurse.all
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts or /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully created." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:name, :date, :period_id, :nurse_id, nurse_ids: [])
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift) do |form| %>
  <% if shift.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.text_field :date %>
  </div>

  <div>
    <%= form.label :period_id, style: "display: block" %>
    <%= form.text_field :period_id %>
  </div>

  <div>
    <%= form.label :nurse_id, style: "display: block" %>
    <%= form.text_field :nurse_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/_shift.html.erb
<div id="<%= dom_id shift %>">
  <p>
    <strong>Name:</strong>
    <%= shift.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= shift.date %>
  </p>

  <p>
    <strong>Period:</strong>
    <%#= shift.period_id %>
  </p>

  <p>
    <strong>Nurse:</strong>
    <%#= shift.nurse_id %>
  </p>

</div>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render "form", shift: @shift %>

<br>

<div>
  <%= link_to "Show this shift", @shift %> |
  <%= link_to "Back to shifts", shifts_path %>
</div>

app/views/shifts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shifts</h1>

<div id="shifts">
  <% @shifts.each do |shift| %>
    <%= render shift %>
    <p>
      <%= link_to "Show this shift", shift %>
    </p>
  <% end %>
</div>

<%= link_to "New shift", new_shift_path %>

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render "form", shift: @shift %>

<br>

<div>
  <%= link_to "Back to shifts", shifts_path %>
</div>

app/views/shifts/show.html copy.erb
<div>
<%= form_with(model: Assignment.new , shift_assignments_path(@shift)) do |form|%>
  <%= form.collection_select( :nurse_ids, Nurse.all.map, :id, :name, {include_blank: true,  include_hidden: false , multiple: true, class:""} ) %>
  <%= form.submit "Create Assignment", class: "btn btn-primary" %>
  <%#= submit_tag "Add Nurse", class: "btn btn-primary" %>
<% end %>
</div>
<div>
  <%#= link_to "add new nurse" %>
  <%= link_to "Edit this shift", edit_shift_path(@shift) %> |
  <%= link_to "Back to shifts", shifts_path %>

  <%= button_to "Destroy this shift", @shift, method: :delete %>
</div>

app/views/shifts/show.html.erb
<div>
  <%= link_to "Edit this shift", edit_shift_path(@shift) %> |
  <%= link_to "Back to week", week_path(@shift.week) %>

  <%= button_to "Destroy this shift", @shift, method: :delete %>
</div>

<%= form_with model: Assignment.new, method: :post  do |form| %>
  <%= form.hidden_field :shift_id, value: @shift.id %>
  <%= form.collection_select( :nurse_id, @shift.unassigned_nurses.map, :id, :name, {include_blank: true,  include_hidden: false , multiple: true, class:""} ) %>

  <%= form.submit %>
<% end %>



<br>
<br>
<div>
  <% @shift.nurses.each do |n| %>
    <%= n.name %> <br>
  <% end %>
  
</div>