config/routes.rb
Rails.application.routes.draw do
resources :years do
  resources :weeks, only: :show
end

resources :weeks do
  resources :shifts
  member do
    post 'create_shifts'
    post 'balance_schedule'
  end
end
  

  resources :assignments

  resources :periods
  resources :nurses

  resources :shifts do
    resources :assignments, only: [:create]
    # post 'assigns/new', to: 'assignments#create'
  end 

  # resources :shifts

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "years#index"
end
=begin
 /shifts/:shift_id/assigns(.:format)      

 Started POST "/shifts/16/assigns/new" for ::1 at 2023-01-20 13:15:46 -0800
  
ActionController::RoutingError (No route matches [POST] "/shifts/16/assigns/new"):
=end

app/models/year.rb
class Year < ApplicationRecord

  has_many :weeks, dependent: :destroy


   after_create :create_weeks 

  def create_weeks
    year_object = Year.last
    year = year_object.year_date.to_i

    year = Date.new(year)

    total_weeks_in_year = year.end_of_year.cweek
    year = year.year.to_i
    (1 .. total_weeks_in_year).each do |week|
      # p week
      # p year
    p  start_date = Date.commercial(year, week).beginning_of_week
    p  end_date = Date.commercial(year, week).end_of_week

    week = Week.create!(year_id: year_object.id, week_number: week, start_date: start_date, end_date: end_date)
      
    # week.create_shifts
    (start_date..end_date).each do |date|
      # Shift.create(period_id: self.id, start_time: date.beginning_of_day, end_time: date.end_of_day)
      Shift.create!(week_id: week.id, date: date)
    end

    end
  end
end






=begin
  accepts_nested_attributes_for :weeks
  def create_shifts
    start_date = self.begining_date

    end_date = self.end_date
    (start_date..end_date).each do |date|
      # Shift.create(period_id: self.id, start_time: date.beginning_of_day, end_time: date.end_of_day)
      Shift.create!(period_id: self.id, date: date)
    end
    
  end

  def create_weeks
    # start_date = self.start_date
    # end_date = self.end_date
    (start_date..end_date).each do |date|
      # Shift.create(period_id: self.id, start_time: date.beginning_of_day, end_time: date.end_of_day)
      Week.create!(year_id: self.id, week_number: date)
    end
  end
=end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: %i[ show edit update destroy ]

  # GET /years or /years.json
  def index
    # to list by descending order of create_at, use:
    @years = Year.all.order("created_at DESC")
  end

  # GET /years/1 or /years/1.json
  def show
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years or /years.json
  def create
    @year = Year.new(year_params)

    respond_to do |format|
      if @year.save
        format.html { redirect_to year_url(@year), notice: "Year was successfully created." }
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1 or /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to year_url(@year), notice: "Year was successfully updated." }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1 or /years/1.json
  def destroy
    @year.destroy

    respond_to do |format|
      format.html { redirect_to years_url, notice: "Year was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def year_params
      params.require(:year).permit(:year_date)
    end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.erb
<%= form_with(model: year) do |form| %>
  <% if year.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
        <% year.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :year_date, style: "display: block" %>
    <%= form.text_field :year_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/years/_year.html.erb
<div id="<%= dom_id year %>">
  <p>
    <strong>Year date:</strong>
    <%= year.year_date %>
  </p>

</div>

app/views/years/edit.html.erb
<h1>Editing year</h1>

<%= render "form", year: @year %>

<br>

<div>
  <%= link_to "Show this year", @year %> |
  <%= link_to "Back to years", years_path %>
</div>

app/views/years/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Years</h1>
<%= link_to "New year", new_year_path %>
<br>
<br>
<div id="years">
  <% @years.each do |year| %>
    <%#= render year %>
     <%= link_to year.year_date, year_path(year) %> <%= button_to 'Destroy', year, method: :delete, class:'' %> <br>
    <p>
    </p>
  <% end %>
</div>

app/views/years/new.html.erb
<h1>New year</h1>

<%= render "form", year: @year %>

<br>

<div>
  <%= link_to "Back to years", years_path %>
</div>

app/views/years/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to 'Years', years_path , class:'' %>

<%= render @year %>

<div>
  <%= link_to "Edit this year", edit_year_path(@year) %> |
  <%= link_to "Back to years", years_path %>

  <%= button_to "Destroy this year", @year, method: :delete %>
</div> <br>


<% @year.weeks.each do |w| %>
  <%= link_to w.start_date, year_week_path(@year, w) %> <br>
<% end %>


<br>